#SchoolBell Config
#Sat May 02 21:20:48 EEST 2026
audio.arEnabled=false
audio.arPath=C\:\\Music\\___Artem Neba - kiss fm Feat Kazantip.mp3
audio.device=Headphone (Realtek(R) Audio)
audio.emEnabled=false
audio.emPath=
audio.siEnabled=false
audio.siPath=
dur.arPause=1
dur.arRing=3
dur.emergency=15
dur.regular=5
selectedSchedule=\u0422\u0435\u0441\u0442 3
