#SchoolBell Config
#Sun May 03 19:41:48 EEST 2026
audio.arEnabled=false
audio.arPath=C\:\\Music\\___Artem Neba - kiss fm Feat Kazantip.mp3
audio.device=Headphone (Realtek(R) Audio)
audio.emEnabled=false
audio.emPath=
audio.siEnabled=false
audio.siPath=
dur.arPause=1
dur.arRing=3
dur.emergency=15
dur.regular=5
selectedSchedule=\u0421\u043A\u043E\u0440\u043E\u0447\u0435\u043D\u0438\u0439 2
